#!/bin/bash

set -e

if [[ $USE_LOCAL_DB == "true" ]]; then
  pritunl set-mongodb mongodb://localhost:27017/pritunl
  mkdir -p /data/db
  mongod --fork --logpath /var/log/mongod.log

else
  pritunl set-mongodb mongodb://${MONGODB_HOST}:27017/pritunl
fi

pritunl set app.reverse_proxy true
pritunl set app.server_ssl false # this has to be true when not behind an elb, but when using with an elb, this should be disabled if you're using an ACM cert on the load balancer
pritunl set app.server_port 443 # this should be your web ui port
pritunl start
